# Machine-specific paths
PX4_DIR="$HOME/PX4-Autopilot"
FSC_PEGASUS_ROOT="/home/fsc-jupiter/Source/fsc_PegasusSimulator"
ISAAC_PY="/home/fsc-jupiter/isaacsim/isaac-sim-standalone-5.1.0-linux-x86_64/python_r_fsc.sh"