# Machine-specific paths
PX4_DIR="/home/markz/PX4-Autopilot"
FSC_PEGASUS_ROOT="/home/markz/fsc_PegasusSimulator"
ISAAC_PY="/home/markz/workspaces/isaacsim/isaac-sim-standalone-5.1.0-linux-x86_64/python_r_fsc.sh"
