#!/usr/bin/env python
"""
make_t650_gear_asset.py — one-shot asset edit: AM_xfwd.usda -> AM_T650.usda

The experiment drone is the T650, whose LANDING GEAR is ~7 cm shorter than the
X650 gear the aerial-manipulator asset carries (user, 2026-10-06: airframe
bottom plate to ground 22-23 cm on the T650 vs 29-30 cm on the X650). This
script copies AM_xfwd.usda and shortens the gear in the COPY only; the
original is never touched (the copy is made first and only the copy is saved).

Run under Isaac's python (pxr needed; a SimulationApp is started headless):

    ~/isaacsim/python_r_fsc.sh \
        extensions/.../robotic_arm/utils_model/make_t650_gear_asset.py [--shorten 0.07]

THE EDIT. The gear is part of ONE mesh, /gripper_bat/body/body (550 k points,
convexDecomposition collision, no cooked collision data stored -- PhysX
re-decomposes it at load). Below the frame (body frame): the bottom plate down
to -0.025 m, a small central part to -0.05, then only the strut tubes, then the
skids at -0.275..-0.313 m. Every point BELOW z_split = -0.06 m is compressed
LINEARLY in z toward z_split so the skid bottoms rise by `shorten`:

    z' = z_split + (z - z_split) * k,   k = (z_bot + shorten - z_split) / (z_bot - z_split)

One affine map in z: the straight struts stay straight, the skid tubes become
slightly oval (vertical diameter x k), nothing above z_split moves. The mesh's
local frame differs from /body's only by a rotation about z (AM_xfwd), so z is
the same in both. Mass/inertia are untouched (06 re-authors /body's mass and
inertia at spawn anyway).

After: the gear bottom is ~0.243 m below the body origin (was 0.313) -> the
planner's push_pull_gear_depth, and the plant's resting body height drops by
the same amount (06: PEGASUS_AM_GROUND_BODY_Z, 0.305 -> 0.235).
"""
import argparse
import os
import shutil

ap = argparse.ArgumentParser()
ap.add_argument("--src", default="AM_xfwd.usda")
ap.add_argument("--dst", default="AM_T650.usda")
ap.add_argument("--shorten", type=float, default=0.07, help="how much higher the skid bottoms end [m]")
ap.add_argument("--z-split", type=float, default=-0.06, help="nothing above this (body frame) moves [m]")
ap.add_argument("--force", action="store_true", help="overwrite an existing dst")
args, _ = ap.parse_known_args()

from isaacsim import SimulationApp  # noqa: E402

_app = SimulationApp({"headless": True})

import numpy as np  # noqa: E402  (after SimulationApp: the bundled numpy)
from pxr import Usd, UsdGeom, Vt, Gf  # noqa: E402

import fsc_aerial_manipulation.rotorcraft as _rc  # noqa: E402

ASSETS = os.path.join(os.path.dirname(_rc.__file__), "assets")
src = os.path.join(ASSETS, args.src)
dst = os.path.join(ASSETS, args.dst)
if os.path.abspath(src) == os.path.abspath(dst):
    raise SystemExit("refusing: dst is the source file")
if os.path.exists(dst) and not args.force:
    raise SystemExit(f"{dst} exists (pass --force to regenerate it)")
shutil.copyfile(src, dst)
print(f"copied {src} -> {dst}", flush=True)

stage = Usd.Stage.Open(dst)
mesh = UsdGeom.Mesh(stage.GetPrimAtPath("/gripper_bat/body/body"))
if not mesh:
    raise SystemExit("no /gripper_bat/body/body mesh in the copy")
tc = Usd.TimeCode.Default()
local = np.array(UsdGeom.Xformable(mesh.GetPrim()).GetLocalTransformation(tc))
# the edit assumes the mesh's local z IS the body's z (a rotation about z only, no z offset)
if not (np.allclose(local[2, :3], [0, 0, 1], atol=1e-9) and np.allclose(local[:3, 2], [0, 0, 1], atol=1e-9)
        and abs(local[3, 2]) < 1e-9):
    raise SystemExit(f"the body mesh's local transform is not a pure z-rotation:\n{local}")

pts = np.array(mesh.GetPointsAttr().Get(), float)
z = pts[:, 2]
z_bot = float(z.min())
zs = args.z_split
k = (z_bot + args.shorten - zs) / (z_bot - zs)
low = z < zs
pts[low, 2] = zs + (z[low] - zs) * k
try:
    arr = Vt.Vec3fArray.FromNumpy(pts.astype(np.float32))
except AttributeError:
    arr = Vt.Vec3fArray([Gf.Vec3f(*map(float, p)) for p in pts])
mesh.GetPointsAttr().Set(arr)
ext = [pts.min(axis=0), pts.max(axis=0)]
mesh.GetExtentAttr().Set(Vt.Vec3fArray([Gf.Vec3f(*map(float, e)) for e in ext]))
layer = stage.GetRootLayer()
layer.documentation = (f"AM_T650: {args.src} with the landing gear shortened by {args.shorten:.3f} m "
                       f"(T650 gear; points below z={zs} scaled by k={k:.4f} in z). "
                       f"Generated by make_t650_gear_asset.py.")
layer.Save()
print(f"gear bottom {z_bot:.4f} -> {pts[:, 2].min():.4f} m (body frame); {int(low.sum())} of {len(pts)} "
      f"points moved, k = {k:.4f}; saved {dst}", flush=True)

# verify by reopening the saved copy, and that the source is untouched
chk = Usd.Stage.Open(dst)
p2 = np.array(UsdGeom.Mesh(chk.GetPrimAtPath("/gripper_bat/body/body")).GetPointsAttr().Get(), float)
src_stage = Usd.Stage.Open(src)
p0 = np.array(UsdGeom.Mesh(src_stage.GetPrimAtPath("/gripper_bat/body/body")).GetPointsAttr().Get(), float)
print(f"verify: copy gear bottom {p2[:, 2].min():.4f} m; source gear bottom {p0[:, 2].min():.4f} m (unchanged)",
      flush=True)
_app.close()
