#!/usr/bin/env python
"""Pinned bare-X650 plant for ROS 2 -> PX4 -> HIL torque tests.

The vehicle translation is clamped in each physics callback while orientation
and angular velocity remain untouched.  PX4 is the sole motor-command backend.
The X650's bench-calibrated static MN4014 + 15x5 propeller model is used without
rotor delay so angular acceleration can be compared directly with the torque
generated by force-at-rotor application.

This is a temporary diagnostic application, not a flight example.  Run it
through ``scripts/indoor_sim/start_x650_pinned_direct_actuator_test.sh``.
"""

import csv
import os

import carb
from isaacsim import SimulationApp


simulation_app = SimulationApp(
    {"headless": os.environ.get("X650_TORQUE_TEST_HEADLESS", "0") == "1"}
)

import numpy as np
import omni.timeline
import omni.usd
from omni.isaac.core.world import World
from pxr import Gf, UsdPhysics
from scipy.spatial.transform import Rotation

from fsc_aerial_manipulation.rotorcraft.x650_bare_frame_utils import (
    X650_MAX_ROTOR_VEL,
    X650_MIN_ROTOR_VEL,
    X650_ROLLING_MOMENT_COEFFICIENT,
    X650_ROTOR_CONSTANT,
    X650_USD,
    X650_ZERO_POSITION_ARMED,
    apply_x650_mass_properties,
)
from fsc_aerial_manipulation.utils import add_dome_lighting
from pegasus.simulator.logic.backends.px4_mavlink_backend import (
    PX4MavlinkBackend,
    PX4MavlinkBackendConfig,
)
from pegasus.simulator.logic.backends.ros2_backend import ROS2Backend
from pegasus.simulator.logic.interface.pegasus_interface import PegasusInterface
from pegasus.simulator.logic.thrusters import QuadraticThrustCurve
from pegasus.simulator.logic.vehicles.multirotor import Multirotor, MultirotorConfig
from pegasus.simulator.params import SIMULATION_ENVIRONMENTS


VEHICLE_ID = 0
SPAWN_POSITION = (0.0, 0.0, 1.5)
BODY_PATH = "/World/quadrotor_0/body"
CSV_PATH = os.environ.get("X650_TORQUE_TEST_CSV", "/tmp/x650_pinned_torque.csv")
STEP_LIMIT = int(os.environ.get("X650_TORQUE_TEST_STEPS", "0"))
HEADLESS = os.environ.get("X650_TORQUE_TEST_HEADLESS", "0") == "1"
ROTOR_DIRECTIONS = (-1.0, -1.0, 1.0, 1.0)


class TorqueTestMultirotor(Multirotor):
    """Stock multirotor with propeller animation disabled for clean dynamics."""

    def handle_propeller_visual(self, rotor_number, force, articulation):
        """Do not drive massive rotor joints during the torque measurement."""


def _make_vehicle(pg: PegasusInterface) -> tuple[TorqueTestMultirotor, PX4MavlinkBackend]:
    """Build the instantaneous calibrated X650 with PX4 as motor authority."""

    scaling = X650_MAX_ROTOR_VEL - X650_ZERO_POSITION_ARMED
    mavlink_config = PX4MavlinkBackendConfig(
        {
            "vehicle_id": VEHICLE_ID,
            "connection_type": "tcpin",
            "connection_ip": "127.0.0.1",
            "connection_baseport": 4560,
            # DDS mode changes can stall one PX4 cycle.  This diagnostic must
            # keep stepping rather than deadlocking on that transition.
            "enable_lockstep": False,
            "px4_autolaunch": False,
            "px4_dir": pg.px4_path,
            "px4_vehicle_model": pg.px4_default_airframe,
            "input_offset": [0.0] * 4,
            "input_scaling": [scaling] * 4,
            "zero_position_armed": [X650_ZERO_POSITION_ARMED] * 4,
        }
    )
    px4_backend = PX4MavlinkBackend(mavlink_config)
    state_backend = ROS2Backend(
        vehicle_id=VEHICLE_ID,
        config={
            "namespace": "uav_",
            "pub_sensors": False,
            "pub_graphical_sensors": False,
            "pub_state": True,
            "pub_twist": True,
            "pub_accel": True,
            "pub_twist_inertial": True,
            "pub_tf": False,
            "sub_control": False,
        },
    )

    config = MultirotorConfig()
    config.backends = [px4_backend, state_backend]
    # Deliberately instantaneous for this first torque/acceleration test.  The
    # static constants and limits remain the measured X650 values.
    config.thrust_curve = QuadraticThrustCurve(
        config={
            "rotor_constant": [X650_ROTOR_CONSTANT] * 4,
            "rolling_moment_coefficient": [
                X650_ROLLING_MOMENT_COEFFICIENT
            ]
            * 4,
            "min_rotor_velocity": [X650_MIN_ROTOR_VEL] * 4,
            "max_rotor_velocity": [X650_MAX_ROTOR_VEL] * 4,
            "rot_dir": list(ROTOR_DIRECTIONS),
        }
    )
    vehicle = TorqueTestMultirotor(
        stage_prefix="/World/quadrotor_0",
        usd_file=X650_USD,
        vehicle_id=VEHICLE_ID,
        init_pos=SPAWN_POSITION,
        init_orientation=(0.0, 0.0, 0.0, 1.0),
        config=config,
    )
    apply_x650_mass_properties(vehicle)
    return vehicle, px4_backend


def _wait_for_prim(world: World, path: str, max_frames: int = 300):
    """Allow the referenced X650 USD to resolve before authoring the pin."""

    for _ in range(max_frames):
        prim = world.stage.GetPrimAtPath(path)
        if prim and prim.IsValid():
            return prim
        world.step(render=False)
    raise RuntimeError(f"X650 prim did not resolve: {path}")


def _body_center_and_anchor(body_prim) -> tuple[np.ndarray, np.ndarray]:
    """Resolve the body CoM and its initial world-space anchor."""

    mass_api = UsdPhysics.MassAPI(body_prim)
    center_attr = mass_api.GetCenterOfMassAttr()
    center = center_attr.Get() if center_attr and center_attr.HasValue() else None
    if center is None or not all(np.isfinite(float(x)) for x in center):
        center = Gf.Vec3f(0.0, 0.0, 0.0)
        print(
            "[PIN] body has no finite authored centerOfMass; using body origin",
            flush=True,
        )
    else:
        center = Gf.Vec3f(*map(float, center))

    # Derive the anchor from the resolved body transform, not the vehicle-root
    # spawn request: the corrected X650 asset authors a small body offset under its root.
    body_world = omni.usd.get_world_transform_matrix(body_prim)
    anchor_d = body_world.Transform(Gf.Vec3d(*map(float, center)))
    anchor = Gf.Vec3f(*map(float, anchor_d))
    print(
        f"[PIN] translation callback anchor={tuple(anchor)} bodyCoM={tuple(center)}; "
        "orientation and angular velocity are free",
        flush=True,
    )
    return np.asarray(center, dtype=float), np.asarray(anchor, dtype=float)


class TranslationClamp:
    """Remove translation without applying a joint constraint or body torque."""

    def __init__(self, vehicle, center: np.ndarray, anchor: np.ndarray):
        self._vehicle = vehicle
        self._center = center
        self._anchor = anchor
        dc = vehicle.get_dc_interface()
        self._dc = dc
        self._body = dc.get_rigid_body(BODY_PATH)

    def update(self, _dt: float) -> None:
        """Restore CoM position and zero inertial linear velocity only."""

        pose = self._dc.get_rigid_body_pose(self._body)
        quat = np.asarray((pose.r.x, pose.r.y, pose.r.z, pose.r.w), dtype=float)
        body_position = self._anchor - Rotation.from_quat(quat).apply(self._center)
        pose.p = carb._carb.Float3(*map(float, body_position))
        self._dc.set_rigid_body_pose(self._body, pose)
        self._dc.set_rigid_body_linear_velocity(
            self._body, carb._carb.Float3(0.0, 0.0, 0.0)
        )


class TorqueDiagnostics:
    """Log actual rotor forces, expected body torque, and measured acceleration."""

    HEADER = (
        "step",
        "time_s",
        *(f"control_{i}" for i in range(4)),
        *(f"omega_{i}_rad_s" for i in range(4)),
        *(f"force_{i}_n" for i in range(4)),
        "tau_x_nm",
        "tau_y_nm",
        "tau_z_nm",
        "alpha_x_rad_s2",
        "alpha_y_rad_s2",
        "alpha_z_rad_s2",
        "pin_error_m",
    )

    def __init__(
        self,
        vehicle,
        backend,
        dt: float,
        pin_center: np.ndarray,
        pin_anchor: np.ndarray,
    ):
        self._vehicle = vehicle
        self._backend = backend
        self._dt = dt
        self._pin_center = pin_center
        self._pin_anchor = pin_anchor
        self._previous_omega = None
        self._step = 0
        self._file = open(CSV_PATH, "w", newline="", encoding="utf-8")
        self._writer = csv.writer(self._file)
        self._writer.writerow(self.HEADER)
        self._body = self._vehicle.get_dc_interface().get_rigid_body(BODY_PATH)
        self._rotor_positions = self._read_rotor_positions()
        print(f"[DIAG] rotor positions [m]:\n{self._rotor_positions}", flush=True)
        print(f"[DIAG] writing {CSV_PATH}", flush=True)

    def _read_rotor_positions(self) -> np.ndarray:
        dc = self._vehicle.get_dc_interface()
        body = dc.get_rigid_body(BODY_PATH)
        rotors = [
            dc.get_rigid_body(f"/World/quadrotor_0/rotor{i}") for i in range(4)
        ]
        poses = dc.get_relative_body_poses(body, rotors)
        positions = np.asarray(
            [[pose.p[0], pose.p[1], pose.p[2]] for pose in poses]
        )
        return positions - self._pin_center[None, :]

    def update(self, dt: float) -> None:
        """Sample once per physics callback after vehicle state/backend updates."""

        omega_body = np.asarray(self._vehicle.state.angular_velocity, dtype=float)
        if self._previous_omega is None or dt <= 0.0:
            alpha = np.zeros(3)
        else:
            alpha = (omega_body - self._previous_omega) / dt
        self._previous_omega = omega_body.copy()

        rotor_omega = np.asarray(self._vehicle._thrusters._velocity, dtype=float)
        forces = np.asarray(self._vehicle._thrusters._force, dtype=float)
        controls = np.asarray(self._backend.input_reference(), dtype=float)
        scaling = X650_MAX_ROTOR_VEL - X650_ZERO_POSITION_ARMED
        normalized = np.where(
            controls > 0.0,
            np.clip((controls - X650_ZERO_POSITION_ARMED) / scaling, 0.0, 1.0),
            0.0,
        )

        force_vectors = np.zeros((4, 3))
        force_vectors[:, 2] = forces
        torque = np.cross(self._rotor_positions, force_vectors).sum(axis=0)
        torque[2] += float(self._vehicle._thrusters._rolling_moment)

        # Read PhysX directly after TranslationClamp rather than the cached
        # vehicle state, which was sampled just before the clamp callback.
        pose = self._vehicle.get_dc_interface().get_rigid_body_pose(self._body)
        position = np.asarray((pose.p.x, pose.p.y, pose.p.z), dtype=float)
        attitude = np.asarray((pose.r.x, pose.r.y, pose.r.z, pose.r.w), dtype=float)
        actual_pin = position + Rotation.from_quat(attitude).apply(self._pin_center)
        pin_error = float(np.linalg.norm(actual_pin - self._pin_anchor))

        self._writer.writerow(
            (
                self._step,
                self._step * self._dt,
                *normalized,
                *rotor_omega,
                *forces,
                *torque,
                *alpha,
                pin_error,
            )
        )
        if self._step % 25 == 0:
            self._file.flush()
            print(
                f"[TORQUE] k={self._step:06d} u={normalized.round(3).tolist()} "
                f"F={forces.round(3).tolist()} tau={torque.round(5).tolist()} "
                f"alpha={alpha.round(4).tolist()} pin_err={pin_error:.2e}",
                flush=True,
            )
        self._step += 1

    def close(self) -> None:
        self._file.close()


class PinnedX650Test:
    """Own the world, constrained vehicle, and diagnostic loop."""

    def __init__(self):
        self.timeline = omni.timeline.get_timeline_interface()
        self.pg = PegasusInterface()
        self.pg._world = World(**self.pg._world_settings)
        self.world = self.pg.world
        self.pg.load_environment(SIMULATION_ENVIRONMENTS["Curved Gridroom"])
        add_dome_lighting(
            stage=omni.usd.get_context().get_stage(),
            dome_path="/World/DomeLight",
            intensity=2500.0,
            exposure=0.0,
            color=(1.0, 1.0, 1.0),
        )

        self.vehicle, self.backend = _make_vehicle(self.pg)
        body = _wait_for_prim(self.world, BODY_PATH)
        center, anchor = _body_center_and_anchor(body)
        # Keep normal gravity for physically consistent HIL sensors and PX4
        # arming.  A runtime translation clamp is used because both spherical
        # and nominal translation-only D6 joints locked this articulation's
        # attitude in live tests.
        self.world.reset()
        dt = float(self.pg._world_settings["physics_dt"])
        self.translation_clamp = TranslationClamp(
            self.vehicle, center, anchor
        )
        self.diagnostics = TorqueDiagnostics(
            self.vehicle, self.backend, dt, center, anchor
        )
        self.world.add_physics_callback(
            "x650_translation_clamp", self.translation_clamp.update
        )
        self.world.add_physics_callback("x650_torque_diagnostics", self.diagnostics.update)

    def run(self) -> None:
        self.timeline.play()
        steps = 0
        try:
            while simulation_app.is_running() and (not STEP_LIMIT or steps < STEP_LIMIT):
                self.world.step(render=not HEADLESS)
                steps += 1
        finally:
            self.diagnostics.close()
            self.timeline.stop()
            print(f"[DONE] steps={steps} csv={CSV_PATH}", flush=True)
            simulation_app.close()


def main() -> None:
    """Run the pinned X650 diagnostic fixture."""

    PinnedX650Test().run()


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        carb.log_error(f"Pinned X650 torque test failed: {exc!r}")
        raise
