#!/usr/bin/env python3
"""make_tuned_yaml.py -- the TUNED geometric+L1 controller yaml for the RTF-1 comparison
(2026-10-01).

Input : rtf_profile_20261001/variants/geometric_l1_mirror_sim.yaml (generated by
        make_geometric_mirror_yaml.py: geometric HARDWARE controller values on the
        whole-body MIRROR plant -- the report's v7 geometric flights).
Gains : a json with a "best" dict in geo_bench's keys (kp_xy, kv_xy, kp_z, kv_z,
        kr_xy, kw_xy, kr_z, kw_z, as_v, as_w, omega_c).
Output: variants/geometric_l1_mirror_sim_tuned.yaml -- the input with ONLY those 17
        yaml keys (x/y pairs share one value) and vehicle_name changed, CHECKED:
        every other line is byte-identical, so the plant (sim_*), guards, allocator,
        SAFETY loop, arm model, r_os trim and every limit are exactly the v7 flights'.

    /usr/bin/python3 make_tuned_yaml.py --gains ../analysis/geo_final_gains.json
"""
import argparse
import json
import os
import re

import geo_bench as GB

HERE = os.path.dirname(os.path.abspath(__file__))
KEY = re.compile(r"^(\s+)([a-z][a-z0-9_]*):\s*([^#\n]*?)\s*(#.*)?$")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gains", required=True)
    ap.add_argument("--src", default=GB.MIRROR_YAML)
    ap.add_argument("--out", default=os.path.join(HERE, "..", "variants", "geometric_l1_mirror_sim_tuned.yaml"))
    ap.add_argument("--vehicle-name", default="AM-T650-L1-MIRROR-TUNED")
    ap.add_argument("--digits", type=int, default=4, help="significant digits written")
    a = ap.parse_args()
    g = json.load(open(a.gains))["best"]
    missing = [k for k in GB.GAIN_KEYS if k not in g]
    if missing:
        raise SystemExit(f"gains file lacks {missing}")
    target = {}
    for k in GB.GAIN_KEYS:
        v = float(f"{g[k]:.{a.digits}g}")
        for yk in GB.YAML_KEYS[k]:
            target[yk] = v
    src = open(a.src).read().splitlines()
    out, changed, seen = [], [], set()
    for line in src:
        m = KEY.match(line)
        if m and m.group(2) in target and m.group(2) not in seen:
            seen.add(m.group(2))
            new = f"{target[m.group(2)]!r}"
            changed.append((m.group(2), m.group(3), new))
            out.append(f"{m.group(1)}{m.group(2)}: {new}  # TUNED 2026-10-01 (was {m.group(3)}; "
                       f"geometric_l1_tune_20261001)")
        elif m and m.group(2) == "vehicle_name":
            changed.append(("vehicle_name", m.group(3), f'"{a.vehicle_name}"'))
            out.append(f'{m.group(1)}vehicle_name: "{a.vehicle_name}"')
        else:
            out.append(line)
    if set(target) - seen:
        raise SystemExit(f"keys not found in {a.src}: {sorted(set(target) - seen)}")
    header = [
        "# " + "=" * 76,
        "# GENERATED -- do not hand-edit. fsc_PegasusSimulator",
        "#   docs/docs_aerial_manipulator/geometric_l1_tune_20261001/tools/make_tuned_yaml.py",
        "# = rtf_profile_20261001/variants/geometric_l1_mirror_sim.yaml with the geometric+L1",
        "#   law's GAINS replaced by the 2026-10-01 bench tune (" + os.path.basename(a.gains) + ").",
        "#   Plant, guards, allocator, SAFETY loop, arm model and limits are untouched.",
        "#   SIMULATION ONLY -- never flown on hardware.",
        "# " + "=" * 76, ""]
    open(a.out, "w").write("\n".join(header + out) + "\n")
    # ---- checks ----
    new_lines = open(a.out).read().splitlines()[len(header):]
    diff = [(o, n) for o, n in zip(src, new_lines) if o != n]
    assert len(new_lines) == len(src)
    assert len(diff) == len(changed), (len(diff), len(changed))
    cfg = GB.GeoConfig(a.out)
    for k in GB.GAIN_KEYS:
        assert abs(cfg.gains_in_yaml[k] - float(f"{g[k]:.{a.digits}g}")) < 1e-12, k
    print(f"wrote {os.path.normpath(a.out)}: {len(changed)} lines changed, all others byte-identical")
    for k, old, new in changed:
        print(f"  {k}: {old} -> {new}")


if __name__ == "__main__":
    main()
