#!/usr/bin/env bash
# am_plant_from_yaml.sh -- the aerial manipulator's PLANT knobs, read from a
# controller yaml's section-1 REALITY MODEL and exported as the PEGASUS_* env
# the Isaac plant script (06) consumes (2026-09-18).
#
# Sourced, not executed. Set WB_SIM_YAML before sourcing. Exports:
#   PEGASUS_ARM_SERVO_MODEL, PEGASUS_ARM_CURRENT_NOISE_{A,BW_HZ,SEED},
#   PEGASUS_PLANT_{MASS,INERTIA}_SCALE, PEGASUS_PLANT_COM_SHIFT_{X,Y,Z},
#   PEGASUS_PLANT_KF_SCALE, PEGASUS_ARM_COUNTS_{ENABLE,NOMINAL,TRUE},
#   PEGASUS_ARM_FRICTION_{SCALE,WIDTH}, PEGASUS_ARM_MASS_SCALE,
#   PEGASUS_ARM_FRICTION_COMP, and sets ARM_PT_CORR (true|false) for the
#   torque-mode arm stack's passthrough_corrections:= argument.
# Precedence everywhere: environment > yaml > built-in default.
#
# THIS IS A VERBATIM COPY of the block in
# start_t650_aerial_manipulator_whole_body_L1_adaptive_4D_direct_actuation_sitl.sh
# (lines "ARM SERVO MODEL" .. "ARM GRAVITY MISMATCH"), lifted so that the
# DECOUPLED rig (start_t650_aerial_manipulator_geometric_L1_adaptive_direct_actuation_sitl.sh)
# reads its own yaml's identical section with identical semantics. The WB
# launchers still carry the block inline on purpose -- they fly tomorrow and
# were not touched; fold them onto this file after the flight test. Keep the
# two in step until then (diff them).
# -- ARM SERVO MODEL: the current loop's residual, in the plant (2026-09-09) ---
# THE SWITCH LIVES HERE, not in the controller YAML: this is a property of the
# PLANT, and the paired fsc_autopilot_ros2 node never sees it -- that mismatch
# is the effect under test. The arm controller now closes a 1.5 Hz software
# CURRENT LOOP around Dynamixel Mode 16, which REMOVES the back-EMF droop this
# block used to carry (j2 torque delivery 93.3 -> 99.4 %, j3 87.5 -> 91.8 %) and
# leaves a zero-mean residual current error in its place. Design and bench
# numbers: fsc_open_manipulator/doc/"Current Loop Design.md" and
# doc/current_error_all.png; implementation in .../robotic_arm/servo_model.py.
#
#   current  ON  - the arm as it is today: residual current noise, band-limited
#                  at 5 Hz, made torque through Kt
#   ideal    OFF - the commanded effort applied exactly, for the A/B
#
# THE RESIDUAL IS PER JOINT (2026-09-11), and the asymmetry is the plant: the
# arm ships current_loop_bandwidth_hz_joints [0.0, 1.5, 1.5, 0.0], because the
# trim helps the two loaded joints and HURTS j1/j4, whose commanded current is
# mostly noise. So the two joints with NO trim are the two NOISIEST -- in-band
# bench rms 11 / 4.4 / 6.8 / 11 mA, which this file's yaml carries as the total
# rms [15.6, 6.2, 9.6, 15.6] mA (a first-order low pass puts half its variance
# below its own corner, so total = sqrt(2) x in-band).
#
# Override without editing this file:
#   PEGASUS_ARM_SERVO_MODEL=ideal <this script> <config>
# The SOURCE OF TRUTH is the paired controller yaml, so one file describes the
# whole run (user request, 2026-09-04). The whole-body NODE never declares these
# keys -- rclcpp ignores them -- they are here for the plant, which is why they
# are prefixed sim_ and why this launcher is what reads them.
# Precedence: environment > yaml > built-in default.
# WHICH SIM CONFIG (2026-09-26, user request). Two 4-D sim yamls exist:
#   mirror      ..._l1_4d_..._sim.yaml             the EXPERIMENT MIRROR: the
#               hardware controller config verbatim + the plant identified
#               from the 0918/0921/0924 flights (sim2real_tuning_20260926)
#   robustness  ..._l1_4d_..._sim_robustness.yaml  the stress plant (config A:
#               +17.6 % allocator kf, mass/inertia x1.10, CoM shift, ...)
#   pick_and_place  ..._l1_4d_..._sim_pick_and_place.yaml  the mirror + the tuned
#               pick-and-place planner block (07's scene; GENERATED by
#               docs/docs_aerial_manipulator/pick_place_tune_20261001/tools/make_pick_place_yaml.py)
#   push_pull   ..._l1_4d_..._sim_push_pull.yaml   the mirror + the push-and-pull
#               planner block (07 push-and-pull scene; GENERATED by
#               docs/docs_aerial_manipulator/archive/push_pull_20261003/tools/make_push_pull_yaml.py)
# WB_SIM_PROFILE picks one (default mirror); WB_SIM_YAML (a path) overrides.
# The paired stack scripts read the SAME two variables, so one setting
# describes the whole run.
WB_SIM_PROFILE="${WB_SIM_PROFILE:-mirror}"
case "$WB_SIM_PROFILE" in
  mirror)     _WB_SIM_SUFFIX="_sim.yaml" ;;
  robustness) _WB_SIM_SUFFIX="_sim_robustness.yaml" ;;
  pick_and_place|pick_place) _WB_SIM_SUFFIX="_sim_pick_and_place.yaml" ;;   # the mirror + the pick-and-place gains and planner block (pick_place = the old alias)
  push_pull)  _WB_SIM_SUFFIX="_sim_push_pull.yaml" ;;    # the mirror + the push-and-pull planner block
  *) echo "ERROR: WB_SIM_PROFILE must be 'mirror', 'robustness', 'pick_and_place' or 'push_pull' (got '$WB_SIM_PROFILE')" >&2; exit 2 ;;
esac
WB_SIM_YAML="${WB_SIM_YAML:-$FSC_AUTOPILOT_WS/src/fsc_autopilot_ros2/config/params_single_aerial_manipulator_whole_body_l1_4d_direct_actuation_t650${_WB_SIM_SUFFIX}}"
[[ -r "$WB_SIM_YAML" ]] || { echo "ERROR: plant config not found: $WB_SIM_YAML" >&2; exit 2; }
echo -e "\033[1;36mPLANT CONFIG: $(basename "$WB_SIM_YAML") (WB_SIM_PROFILE=$WB_SIM_PROFILE)\033[0m"
# Which lag knobs the CALLER set explicitly (the wall-clock compensation at the
# end of this file never rescales a value the caller chose -- replay.sh, for one,
# exports them already converted).
_WC_ENV_LAMBDA="${PEGASUS_PLANT_ROTOR_LAMBDA:+1}"
_WC_ENV_VLAG="${PEGASUS_ARM_VEL_LAG_S:+1}"
_WC_ENV_NBW="${PEGASUS_ARM_CURRENT_NOISE_BW_HZ:+1}"
yaml_scalar() {  # $1 = key; prints the value, or nothing if absent/commented
  [[ -r "$WB_SIM_YAML" ]] || return 0
  sed -nE "s/^[[:space:]]*$1:[[:space:]]*([^#[:space:]]+).*/\\1/p" "$WB_SIM_YAML" | head -1
}
if [[ -z "${PEGASUS_ARM_SERVO_MODEL:-}" ]]; then
  case "$(yaml_scalar sim_arm_current_noise_enable)" in
    true|True|TRUE|1)    PEGASUS_ARM_SERVO_MODEL=current ;;
    false|False|FALSE|0) PEGASUS_ARM_SERVO_MODEL=ideal ;;
    "") PEGASUS_ARM_SERVO_MODEL=current
        echo "NOTE: sim_arm_current_noise_enable not found in $WB_SIM_YAML -- defaulting to 'current'." ;;
    *)  echo "ERROR: sim_arm_current_noise_enable must be true or false in $WB_SIM_YAML" >&2; exit 2 ;;
  esac
  if [[ "$PEGASUS_ARM_SERVO_MODEL" != "ideal" ]]; then
    for KV in "PEGASUS_ARM_CURRENT_NOISE_BW_HZ:sim_arm_current_noise_bw_hz" \
              "PEGASUS_ARM_CURRENT_NOISE_SEED:sim_arm_current_noise_seed"; do
      VAR="${KV%%:*}"; KEY="${KV##*:}"
      if [[ -z "${!VAR:-}" ]]; then
        V="$(yaml_scalar "$KEY")"
        [[ -n "$V" ]] && export "$VAR=$V"
      fi
    done
    # The amplitude is PER JOINT: sim_arm_current_noise_a_j1..j4, joined into
    # the "a1,a2,a3,a4" form 06 parses. ALL FOUR OR NONE -- a partial list
    # would silently model three joints, the same rule the counts block uses.
    # The pre-2026-09-11 scalar sim_arm_current_noise_a still works as a
    # fallback, so an older yaml keeps its meaning.
    if [[ -z "${PEGASUS_ARM_CURRENT_NOISE_A:-}" ]]; then
      NOISE_LIST=""
      for J in j1 j2 j3 j4; do
        V="$(yaml_scalar "sim_arm_current_noise_a_$J")"
        [[ -n "$V" ]] || { NOISE_LIST=""; break; }
        NOISE_LIST="${NOISE_LIST:+$NOISE_LIST,}$V"
      done
      [[ -z "$NOISE_LIST" ]] && NOISE_LIST="$(yaml_scalar sim_arm_current_noise_a)"
      [[ -n "$NOISE_LIST" ]] && export PEGASUS_ARM_CURRENT_NOISE_A="$NOISE_LIST"
    fi
  fi
  echo "Arm servo model taken from $(basename "$WB_SIM_YAML")"
fi
export PEGASUS_ARM_SERVO_MODEL="${PEGASUS_ARM_SERVO_MODEL:-current}"

# ── ROBUSTNESS INJECTION: plant-side model uncertainty ──────────────────────
# Same precedence rule as the servo model: environment > yaml > built-in.
# Absent keys leave the plant nominal, so a yaml without them behaves as before.
for KV in "PEGASUS_PLANT_MASS_SCALE:sim_plant_mass_scale" \
          "PEGASUS_PLANT_INERTIA_SCALE:sim_plant_inertia_scale" \
          "PEGASUS_PLANT_COM_SHIFT_X:sim_plant_com_shift_x" \
          "PEGASUS_PLANT_COM_SHIFT_Y:sim_plant_com_shift_y" \
          "PEGASUS_PLANT_COM_SHIFT_Z:sim_plant_com_shift_z" \
          "PEGASUS_PLANT_KF_SCALE:sim_plant_kf_scale"; do
  VAR="${KV%%:*}"; KEY="${KV##*:}"
  if [[ -z "${!VAR:-}" ]]; then
    V="$(yaml_scalar "$KEY")"
    [[ -n "$V" ]] && export "$VAR=$V"
  fi
done
if [[ -n "${PEGASUS_PLANT_MASS_SCALE:-}${PEGASUS_PLANT_INERTIA_SCALE:-}${PEGASUS_PLANT_COM_SHIFT_X:-}${PEGASUS_PLANT_COM_SHIFT_Y:-}${PEGASUS_PLANT_COM_SHIFT_Z:-}" ]]; then
  echo -e "\033[1;31mMODEL-UNCERTAINTY INJECTION ACTIVE: mass x${PEGASUS_PLANT_MASS_SCALE:-1.0}, inertia x${PEGASUS_PLANT_INERTIA_SCALE:-1.0}, CoM shift (${PEGASUS_PLANT_COM_SHIFT_X:-0},${PEGASUS_PLANT_COM_SHIFT_Y:-0},${PEGASUS_PLANT_COM_SHIFT_Z:-0}) m\033[0m"
fi
if [[ -n "${PEGASUS_PLANT_KF_SCALE:-}" && "${PEGASUS_PLANT_KF_SCALE}" != "1.0" ]]; then
  # A PLANT-side k_f error is seen by SAFETY and DIRECT alike, unlike an
  # alloc_thrust_coeff detune which only DIRECT goes through.
  echo -e "\033[1;31mTHRUST-LOSS INJECTION ACTIVE (PLANT SIDE, both modes): k_f x${PEGASUS_PLANT_KF_SCALE}\033[0m"
  echo -e "\033[1;33mThe PLANT is perturbed; the controller believes the nominal model.\033[0m"
fi

# ── ARM COUNT <-> TORQUE: the digital command path ──────────────────────────
# The real arm command is an int16 Goal PWM register, not a torque. Same
# precedence rule again: environment > yaml > built-in. Absent keys leave the
# arm a perfectly calibrated continuous torque source, i.e. the pre-2026-09-08
# plant, so a yaml without them behaves exactly as before.
if [[ -z "${PEGASUS_ARM_COUNTS_ENABLE:-}" ]]; then
  case "$(yaml_scalar sim_arm_counts_enable)" in
    true|True|TRUE|1)    export PEGASUS_ARM_COUNTS_ENABLE=1 ;;
    false|False|FALSE|0) export PEGASUS_ARM_COUNTS_ENABLE=0 ;;
    "")                  export PEGASUS_ARM_COUNTS_ENABLE=0 ;;
    *)  echo "ERROR: sim_arm_counts_enable must be true or false in $WB_SIM_YAML" >&2; exit 2 ;;
  esac
fi
for KV in "PEGASUS_ARM_COUNTS_NOMINAL:sim_arm_counts_nominal" \
          "PEGASUS_ARM_COUNTS_TRUE:sim_arm_counts_true"; do
  VAR="${KV%%:*}"; KEY="${KV##*:}"
  [[ -n "${!VAR:-}" ]] && continue
  LIST=""
  for J in j1 j2 j3 j4; do
    V="$(yaml_scalar "${KEY}_$J")"
    # All four or none: a partial list would silently model three joints.
    [[ -n "$V" ]] || { LIST=""; break; }
    LIST="${LIST:+$LIST,}$V"
  done
  [[ -n "$LIST" ]] && export "$VAR=$LIST"
done
# Only claim ACTIVE when something actually changes: quantization on, or the
# two calibrations genuinely differ. Setting TRUE to the nominal value is a
# MATCHED run and must not look like an injection -- a banner that fires either
# way is worth nothing.
ARM_COUNTS_MISMATCH=0
if [[ -n "${PEGASUS_ARM_COUNTS_TRUE:-}" ]]; then
  ARM_COUNTS_MISMATCH=$(awk -v a="${PEGASUS_ARM_COUNTS_NOMINAL:-162.4,154.0,150.5,153.4}" \
                            -v b="$PEGASUS_ARM_COUNTS_TRUE" '
    BEGIN { n=split(a,A,","); split(b,B,",");
            for (i=1;i<=n;i++) if ((A[i]-B[i])^2 > 1e-18) { print 1; exit } print 0 }')
fi
if [[ "${PEGASUS_ARM_COUNTS_ENABLE:-0}" == "1" || "$ARM_COUNTS_MISMATCH" == "1" ]]; then
  echo -e "\033[1;31mARM COUNT<->TORQUE PATH ACTIVE: register quantized=${PEGASUS_ARM_COUNTS_ENABLE:-0}, counts/N.m nominal [${PEGASUS_ARM_COUNTS_NOMINAL:-calibrated}] vs true [${PEGASUS_ARM_COUNTS_TRUE:-calibrated}]\033[0m"
  if [[ "$ARM_COUNTS_MISMATCH" == "1" ]]; then
    echo -e "\033[1;33mDelivered torque scales as nominal/true; the controller is not told. Isaac prints the percentage.\033[0m"
  else
    echo -e "\033[1;33mCalibration MATCHED: register quantization only, no gain error.\033[0m"
  fi
else
  echo "Arm count<->torque path off: continuous torque, perfect calibration."
fi

# ── GEARBOX FRICTION + ARM GRAVITY MISMATCH (2026-09-14) ─────────────────────
# The calibration report's friction (eq. 5) on the PLANT, scaled, and the arm
# link masses scaled -- while the flight law, the arm controller's correction
# and 06's own hold keep the nominal arm. 1.05 / 1.05 = the requested 5 %
# imperfect friction + gravity compensation. Same precedence: env > yaml >
# built-in (0 / 1.0 = the pre-2026-09-14 plant).
# The friction scale may be PER JOINT (sim_arm_friction_scale_j1..j4, all four
# or none -- the 0924 flights put j2 and j3 at different fractions of the
# report's model); the scalar sim_arm_friction_scale is the fallback.
if [[ -z "${PEGASUS_ARM_FRICTION_SCALE:-}" ]]; then
  FR_LIST=""
  for J in j1 j2 j3 j4; do
    V="$(yaml_scalar "sim_arm_friction_scale_$J")"
    [[ -n "$V" ]] || { FR_LIST=""; break; }
    FR_LIST="${FR_LIST:+$FR_LIST,}$V"
  done
  [[ -n "$FR_LIST" ]] && export PEGASUS_ARM_FRICTION_SCALE="$FR_LIST"
fi
for KV in "PEGASUS_ARM_FRICTION_SCALE:sim_arm_friction_scale" \
          "PEGASUS_ARM_FRICTION_WIDTH:sim_arm_friction_width" \
          "PEGASUS_ARM_MASS_SCALE:sim_arm_mass_scale"; do
  VAR="${KV%%:*}"; KEY="${KV##*:}"
  if [[ -z "${!VAR:-}" ]]; then
    V="$(yaml_scalar "$KEY")"
    [[ -n "$V" ]] && export "$VAR=$V"
  fi
done
# THE COMPENSATION IS COUPLED TO THE PLANT. The arm controller's friction
# feed-forward (torque_controller_isaac_aerial.yaml, passthrough_auxiliary_terms)
# is switched ON exactly when the plant has friction, and OFF when it has none
# -- a feed-forward against a frictionless plant is a pure disturbance.
# PEGASUS_ARM_FRICTION_COMP=0|1 overrides (the "uncompensated" A/B).
_fr_max() { awk -v s="${1:-0}" 'BEGIN{n=split(s,A,","); m=0; for(i=1;i<=n;i++) if (A[i]+0>m) m=A[i]+0; print m}'; }
if [[ -z "${PEGASUS_ARM_FRICTION_COMP:-}" ]]; then
  if awk -v s="$(_fr_max "${PEGASUS_ARM_FRICTION_SCALE:-0}")" 'BEGIN{exit !(s+0 > 0)}'; then
    export PEGASUS_ARM_FRICTION_COMP=1
  else
    export PEGASUS_ARM_FRICTION_COMP=0
  fi
fi
case "$PEGASUS_ARM_FRICTION_COMP" in 0|1) ;;
  *) echo "ERROR: PEGASUS_ARM_FRICTION_COMP must be 0 or 1 (got '$PEGASUS_ARM_FRICTION_COMP')" >&2; exit 2 ;;
esac
ARM_PT_CORR=$([[ "$PEGASUS_ARM_FRICTION_COMP" == 1 ]] && echo true || echo false)
if awk -v s="$(_fr_max "${PEGASUS_ARM_FRICTION_SCALE:-0}")" 'BEGIN{exit !(s+0 > 0)}'; then
  echo -e "\033[1;31mGEARBOX FRICTION ACTIVE on the plant: x${PEGASUS_ARM_FRICTION_SCALE} the report's fc/mu (tanh width ${PEGASUS_ARM_FRICTION_WIDTH:-0.015} rad/s); arm-side friction compensation ${ARM_PT_CORR} (passthrough_auxiliary_terms).\033[0m"
else
  echo "Gearbox friction off (frictionless plant); arm-side friction compensation ${ARM_PT_CORR}."
fi
if [[ -n "${PEGASUS_ARM_MASS_SCALE:-}" && "${PEGASUS_ARM_MASS_SCALE}" != "1.0" ]]; then
  echo -e "\033[1;31mARM GRAVITY MISMATCH ACTIVE: arm link masses x${PEGASUS_ARM_MASS_SCALE}; every model keeps the nominal arm.\033[0m"
fi

# ── SIM-TO-REAL MIRROR KNOBS (2026-09-26, sim2real_tuning_20260926) ─────────
# Identified from the 0918/0921/0924 whole-body flights; each defaults to
# "off" in 06, so a yaml without them flies the plant exactly as before.
#   sim_plant_km_scale          x on the yaw (rolling-moment) coefficient only
#   sim_plant_rotor_lambda      rotor spin-up bandwidth [1/s] (effective lag)
#   sim_plant_kf_sag_per_min    battery sag, fractional kf loss per minute
#   sim_plant_force_bias_{x,y,z}  body-fixed FLU force  [N]   standing wrench
#   sim_plant_torque_bias_{x,y,z} body-fixed FLU torque [N.m] the airframe carries
#   sim_arm_vel_lag_s           Present-Velocity lag on the REPORTED joint rate
#   sim_arm_vel_quant_rad_s     its quantum (0.024 rad/s)
for KV in "PEGASUS_PLANT_KM_SCALE:sim_plant_km_scale" \
          "PEGASUS_PLANT_ROTOR_LAMBDA:sim_plant_rotor_lambda" \
          "PEGASUS_PLANT_KF_SAG_PER_MIN:sim_plant_kf_sag_per_min" \
          "PEGASUS_ARM_VEL_LAG_S:sim_arm_vel_lag_s" \
          "PEGASUS_ARM_VEL_QUANT:sim_arm_vel_quant_rad_s"; do
  VAR="${KV%%:*}"; KEY="${KV##*:}"
  if [[ -z "${!VAR:-}" ]]; then
    V="$(yaml_scalar "$KEY")"
    [[ -n "$V" ]] && export "$VAR=$V"
  fi
done
for KV in "PEGASUS_PLANT_FORCE_BIAS:sim_plant_force_bias" \
          "PEGASUS_PLANT_TORQUE_BIAS:sim_plant_torque_bias"; do
  VAR="${KV%%:*}"; KEY="${KV##*:}"
  [[ -n "${!VAR:-}" ]] && continue
  LIST=""
  for AX in x y z; do
    V="$(yaml_scalar "${KEY}_$AX")"
    [[ -n "$V" ]] || { LIST=""; break; }   # all three or none
    LIST="${LIST:+$LIST,}$V"
  done
  [[ -n "$LIST" ]] && export "$VAR=$LIST"
done
# sim_arm_armature_j1..j4: the servos' reflected rotor inertia on the PLANT
# (PhysX joint armature, kg m^2), all four or none -> PEGASUS_ARM_ARMATURE.
# Absent = 06's 0.020 on every joint. The mirror yaml carries the ground-bench
# calibration (arm_armature_20260926/bench/README.md).
if [[ -z "${PEGASUS_ARM_ARMATURE:-}" ]]; then
  LIST=""
  for J in 1 2 3 4; do
    V="$(yaml_scalar "sim_arm_armature_j$J")"
    [[ -n "$V" ]] || { LIST=""; break; }
    LIST="${LIST:+$LIST,}$V"
  done
  [[ -n "$LIST" ]] && export PEGASUS_ARM_ARMATURE="$LIST"
fi
MIRROR_TXT=""
[[ -n "${PEGASUS_PLANT_KM_SCALE:-}" && "${PEGASUS_PLANT_KM_SCALE}" != "1.0" ]] && MIRROR_TXT+=" km x${PEGASUS_PLANT_KM_SCALE};"
[[ -n "${PEGASUS_PLANT_ROTOR_LAMBDA:-}" ]] && MIRROR_TXT+=" lambda ${PEGASUS_PLANT_ROTOR_LAMBDA} 1/s;"
[[ -n "${PEGASUS_PLANT_KF_SAG_PER_MIN:-}" && "${PEGASUS_PLANT_KF_SAG_PER_MIN}" != "0.0" ]] && MIRROR_TXT+=" kf sag ${PEGASUS_PLANT_KF_SAG_PER_MIN}/min;"
[[ -n "${PEGASUS_PLANT_FORCE_BIAS:-}" ]] && MIRROR_TXT+=" force bias (${PEGASUS_PLANT_FORCE_BIAS}) N;"
[[ -n "${PEGASUS_PLANT_TORQUE_BIAS:-}" ]] && MIRROR_TXT+=" torque bias (${PEGASUS_PLANT_TORQUE_BIAS}) N.m;"
[[ -n "${PEGASUS_ARM_VEL_LAG_S:-}" && "${PEGASUS_ARM_VEL_LAG_S}" != "0.0" ]] && MIRROR_TXT+=" arm vel lag ${PEGASUS_ARM_VEL_LAG_S} s;"
[[ -n "${PEGASUS_ARM_VEL_QUANT:-}" && "${PEGASUS_ARM_VEL_QUANT}" != "0.0" ]] && MIRROR_TXT+=" arm vel quantum ${PEGASUS_ARM_VEL_QUANT} rad/s;"
[[ -n "${PEGASUS_ARM_ARMATURE:-}" ]] && MIRROR_TXT+=" arm armature (${PEGASUS_ARM_ARMATURE}) kg m^2;"
if [[ -n "$MIRROR_TXT" ]]; then
  echo -e "\033[1;35mSIM-TO-REAL MIRROR TERMS (as written, plant time):${MIRROR_TXT}\033[0m"
else
  echo "Sim-to-real mirror terms: none (plant as before)."
fi

# ── WALL-CLOCK COMPENSATION (2026-09-27) ────────────────────────────────────
# The whole-body law, its observers and the planner run on the WALL clock, and
# this desktop runs Isaac + PX4 at RTF ~0.48. A plant lag of tau PLANT seconds
# therefore reaches the law as tau/RTF wall seconds: the MN4010 rotor pole at
# its physical 10.03 1/s looks like ~200 ms of lag instead of 100 ms, and the
# hardware gains lose their margin. That is why the mirror plant DIVERGED in
# DIRECT through the plain §7.17.1 launch (2026-09-27, tilt watchdog 14 s after
# entry) while every replay.sh flight of the same yaml flew -- replay.sh has
# expressed these lags in wall time since 2026-09-26 (f18_r1 was the lesson).
# Opt-in per yaml: sim_wall_clock_compensation: true (the MIRROR sets it; the
# robustness yaml does not, so its behaviour is unchanged). The RTF comes from
# PEGASUS_SIM_RTF > the machine config's SIM_RTF > 1.0 (no change). Converted,
# as replay.sh does: rotor lambda / RTF, arm-velocity lag x RTF, current-noise
# corner / RTF. A value the caller set in the environment is left alone. The
# yaml keeps the physical, plant-time numbers.
case "$(yaml_scalar sim_wall_clock_compensation)" in
  true|True|TRUE|1) _WC_ON=1 ;;
  *)                _WC_ON=0 ;;
esac
_WC_RTF="${PEGASUS_SIM_RTF:-${SIM_RTF:-1.0}}"
if [[ "$_WC_ON" == 1 ]]; then
  if ! awk -v r="$_WC_RTF" 'BEGIN{exit !(r+0 > 0.05 && r+0 <= 1.0)}'; then
    echo "ERROR: sim RTF must be in (0.05, 1.0] (got '$_WC_RTF' from PEGASUS_SIM_RTF / SIM_RTF)" >&2; exit 2
  fi
  if [[ -z "${PEGASUS_SIM_RTF:-}${SIM_RTF:-}" ]]; then
    echo -e "\033[1;33mWALL-CLOCK COMPENSATION requested by $(basename "$WB_SIM_YAML") but this machine declares no SIM_RTF (machine config) and PEGASUS_SIM_RTF is unset -- assuming real time. If Isaac runs slower than real time here, the plant lags reach the law stretched by 1/RTF (measure it: rtf_of() in docs/docs_aerial_manipulator/sim2real_tuning_20260926/tools/compare.py, sensor_combined stamps vs receive time).\033[0m"
  fi
  if awk -v r="$_WC_RTF" 'BEGIN{exit !(r+0 < 0.999)}'; then
    _WC_TXT=""
    if [[ -z "$_WC_ENV_LAMBDA" && -n "${PEGASUS_PLANT_ROTOR_LAMBDA:-}" ]]; then
      export PEGASUS_PLANT_ROTOR_LAMBDA="$(awk -v l="$PEGASUS_PLANT_ROTOR_LAMBDA" -v r="$_WC_RTF" 'BEGIN{printf "%.4f", l/r}')"
      _WC_TXT+=" rotor lambda -> ${PEGASUS_PLANT_ROTOR_LAMBDA} 1/s;"
    elif [[ -z "${PEGASUS_PLANT_ROTOR_LAMBDA:-}" ]]; then
      echo -e "\033[1;33mWALL-CLOCK COMPENSATION: sim_plant_rotor_lambda absent -- the rotor pole is NOT rescaled.\033[0m"
    fi
    if [[ -z "$_WC_ENV_VLAG" && -n "${PEGASUS_ARM_VEL_LAG_S:-}" ]]; then
      export PEGASUS_ARM_VEL_LAG_S="$(awk -v l="$PEGASUS_ARM_VEL_LAG_S" -v r="$_WC_RTF" 'BEGIN{printf "%.4f", l*r}')"
      _WC_TXT+=" arm vel lag -> ${PEGASUS_ARM_VEL_LAG_S} s;"
    fi
    if [[ -z "$_WC_ENV_NBW" && -n "${PEGASUS_ARM_CURRENT_NOISE_BW_HZ:-}" ]]; then
      export PEGASUS_ARM_CURRENT_NOISE_BW_HZ="$(awk -v b="$PEGASUS_ARM_CURRENT_NOISE_BW_HZ" -v r="$_WC_RTF" 'BEGIN{printf "%.3f", b/r}')"
      _WC_TXT+=" current-noise corner -> ${PEGASUS_ARM_CURRENT_NOISE_BW_HZ} Hz;"
    fi
    echo -e "\033[1;35mWALL-CLOCK COMPENSATION ON (RTF ${_WC_RTF}):${_WC_TXT:- nothing to rescale (all set by the caller)}\033[0m"
  else
    echo "Wall-clock compensation: RTF ${_WC_RTF} -- nothing to rescale."
  fi
else
  echo "Wall-clock compensation off for $(basename "$WB_SIM_YAML") (plant lags passed in plant time)."
fi
