#!/usr/bin/env python3
"""build_report.py -- the comparison report v9 (2026-10-05): the v8 page
(../modular_adaptive_20260930/report.html, the circle comparison as published)
plus

  1. Reference trajectories   (NEW, at the top: the expressions both shapes are
                               generated from, and the parameters of each)
  2. Circle                   (v8's section 1, unchanged numbers)
  3. Figure-8                 (NEW: whole-body vs geometric L1, the sizing, the flights)
  4. Simulation settings      (v8's section 2, renumbered)

Equations are written in LaTeX below and converted to MathML (rendered natively by
the browser, so the page needs no math library, font or stylesheet the artifact
sandbox would block). The converter is latex2mathml; it is only needed to REBUILD:

    /usr/bin/python3 -m pip install --target <dir> latex2mathml
    PYTHONPATH=<dir> /usr/bin/python3 build_report.py --scores ../analysis/fig8_scores.json \
        --top ../figures/fig8_top.png --series ../figures/fig8_series.png --out ../report.html
"""
import argparse
import base64
import json
import os
import re

from latex2mathml.converter import convert

HERE = os.path.dirname(os.path.abspath(__file__))
V8 = os.path.join(HERE, "..", "..", "modular_adaptive_20260930", "report.html")


def m(tex, block=True):
    return convert(tex, display="block" if block else "inline")


def mi(tex):
    return m(tex, block=False)


def img64(path):
    return base64.b64encode(open(path, "rb").read()).decode()


CSS = """
.eq { overflow-x: auto; min-width: 0; padding: 4px 2px; }
.eq math { font-size: 1.08em; }
math { font-family: "Cambria Math", "STIX Two Math", "Latin Modern Math", serif; }
.eqgrid { display: grid; grid-template-columns: minmax(0, 1fr); gap: 6px; }
.eqlabel { font: 600 12px/1.3 var(--body); color: var(--fg-3); letter-spacing: .04em; text-transform: uppercase; }
.sub { font-size: 13.5px; color: var(--fg-2); max-width: 80ch; }
.note { font-size: 13px; color: var(--fg-2); }
.wraptbl td, .wraptbl th { white-space: normal; text-align: left; }
.wraptbl td:not(:first-child) { font-family: var(--body); font-size: 13px; }
.wraptbl td:first-child { min-width: 9em; }
:root { --bad: #b42318; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --bad: #f97066; } }
:root[data-theme="dark"] { --bad: #f97066; }
.bad { color: var(--bad); } .okc { color: var(--good); }
tr.rec td { background: var(--bg); font-weight: 600; color: var(--fg); }
.wraphead th { white-space: normal; vertical-align: bottom; }
.wraphead th:first-child, .wraphead td:first-child { min-width: 4em; }
.wraphead td.nw { white-space: nowrap; }
"""


def section_reference():
    eq_time = m(r"\frac{d\tau}{dt}=s\,\sigma(u),\qquad u=\min\!\left(1,\ \frac{\min(t,\ T-t)}{T_r}\right),\qquad "
                r"\sigma(u)=35u^4-84u^5+70u^6-20u^7,\qquad T=2T_r+\frac{N\,T_{lap}-s\,T_r}{s}")
    eq_circle = m(r"\mathbf p_e(\tau)=\big(r\cos(\theta_0+\omega\tau),\ r\sin(\theta_0+\omega\tau),\ h_e\big)^{\top},"
                  r"\qquad \omega=\frac{2\pi}{T_{lap}},\qquad \bar v=\frac{2\pi r}{T_{lap}}")
    eq_fig8 = m(r"\mathbf p_e(\tau)=\mathbf p_{e0}+R_z(\psi_0-\alpha)\,\big(A\sin\omega\tau,\ B\sin 2\omega\tau,\ 0\big)^{\top},"
                r"\qquad \alpha=\mathrm{atan2}(2B,\,A),\qquad "
                r"\bar v=\frac{1}{T_{lap}}\int_0^{2\pi}\sqrt{A^2\cos^2\phi+4B^2\cos^2 2\phi}\;d\phi")
    eq_att = m(r"\psi_t(\tau)=\mathrm{atan2}\big(\dot p_{e,y},\,\dot p_{e,x}\big),\qquad "
               r"R_e(\tau)=R_z\!\left(\psi_t-\tfrac{\pi}{2}\right)R_x(\beta_e),\qquad "
               r"\mathbf b_{1e}=R_e\mathbf e_1=\big(\sin\psi_t,\ -\cos\psi_t,\ 0\big)^{\top}")
    eq_arm = m(r"q_1=0,\qquad q_2(\tau)=\bar q_2+a_2\sin\frac{2\pi\tau}{P},\qquad P=\frac{T_{lap}}{4},\qquad "
               r"(\psi,\ \beta,\ \gamma)=\mathrm{zxz}\big(R_{tilt}(\mathbf n)^{\top}R_e\big),\qquad "
               r"q_3=\beta-q_2,\qquad q_4=\gamma")
    eq_com = m(r"\mathbf x_c=\mathbf p_e+R_0\big(\mathbf r_{0c}(\mathbf q)-\mathbf r_{0e}(\mathbf q)\big),\qquad "
               r"\mathbf n=\frac{\ddot{\mathbf x}_c+g\,\mathbf e_3}{\lVert\ddot{\mathbf x}_c+g\,\mathbf e_3\rVert},"
               r"\qquad R_0=R_0(\mathbf n,\ \psi)")
    html = r"""
<section aria-label="Reference trajectories">
  <h2>1. Reference trajectories</h2>
  <p class="sub">Both trajectories are generated by the same planner (<code>fsc_trajectory_planner</code>, end-effector trajectory mode) from a prescribed end-effector pose curve, an assigned arm sinusoid and one time law. The planner solves the rest for a dynamically compatible whole-body reference, and every controller in this report receives that same reference. The whole-body and modular laws take it directly. The geometric law takes the base position, velocity, acceleration and yaw that the reference bridge converts from it.</p>

  <div class="eqgrid">
    <div class="eqlabel">Time law (both shapes)</div>
    <div class="eq">@@eq_time@@</div>
    <p class="note">$\tau$ is the shape phase in seconds and $t$ the time since Start. Each run starts and ends at rest: a minimum-snap ramp of $T_r=4$ s, then $N$ laps at the constant rate $s$ (the time scale), then the mirrored ramp-out. On the ramps $\sigma$ rises from 0 to 1 with zero first three derivatives at both ends. All flights here use $N=1$ lap at $s=1$.</p>

    <div class="eqlabel">End-effector position: circle</div>
    <div class="eq">@@eq_circle@@</div>
    <p class="note">Centred on the world vertical axis at the hold's end-effector height $h_e$. The run starts at the circle point on the hold's end-effector bearing $\theta_0$ and turns counter-clockwise.</p>

    <div class="eqlabel">End-effector position: figure-8</div>
    <div class="eq">@@eq_fig8@@</div>
    <p class="note">The lobes cross at the hold's end-effector point $\mathbf p_{e0}$, where the run starts and ends. $A$ is the half-length along the long axis and $B$ the half-width across it. The start tangent lies along the drone's nose $\psi_0$, so the long axis sits at $\psi_0-\alpha$ (45° for $B=A/2$). The right lobe is flown clockwise and the left lobe counter-clockwise, so the yaw rate reverses at the crossing. The mean speed $\bar v$ is the path length of one lap over $T_{lap}$, as the arm ground station computes it.</p>

    <div class="eqlabel">End-effector attitude: claw along the path</div>
    <div class="eq">@@eq_att@@</div>
    <p class="note">The end-effector heading follows the path tangent $\psi_t$, with the fixed fold $\beta_e=55^\circ$ about the horizontal axis $\mathbf b_{1e}$ (the claw points along the direction of travel, 35–40° below the horizontal). $\mathbf b_{1e}$ is the tracked end-effector heading, and its azimuth error is the "EE heading" column of the tables.</p>

    <div class="eqlabel">Arm: the assigned redundancy</div>
    <div class="eq">@@eq_arm@@</div>
    <p class="note">The base-yaw joint $q_1$ is fixed and the shoulder $q_2$ is the assigned sinusoid, four periods per lap on both shapes. The drone yaw $\psi$, the fold $\beta=q_2+q_3$ and the wrist roll $\gamma=q_4$ are the z–x–z angles of the end-effector attitude seen from the tilted airframe, where $R_{tilt}(\mathbf n)$ is the minimal rotation taking $\mathbf e_3$ to the thrust direction $\mathbf n$.</p>

    <div class="eqlabel">System centre of mass: the compatible flat output</div>
    <div class="eq">@@eq_com@@</div>
    <p class="note">The thrust direction depends on the CoM acceleration, which depends on the attitude, so the planner solves this as a fixed point (Picard iteration). $\mathbf x_c$ is fitted as a degree-7 B-spline, $\psi$ and $\mathbf q$ as degree-5 B-splines. The streamed reference is their flat map: $\mathbf x_{cd}$ and its derivatives to snap, the base heading, the end-effector position and heading, and $\mathbf q_d,\ \dot{\mathbf q}_d$.</p>
  </div>

  __PARAMTABLE__
</section>
"""
    html = re.sub(r"\$([^$]+)\$", lambda g: mi(g.group(1)), html)
    for k, v in (("eq_time", eq_time), ("eq_circle", eq_circle), ("eq_fig8", eq_fig8),
                 ("eq_att", eq_att), ("eq_arm", eq_arm), ("eq_com", eq_com)):
        html = html.replace("@@" + k + "@@", v)
    return html


def param_table(sc):
    rows = [
        ("size", "r = 0.5 m", "A = 0.75 m, B = 0.375 m (1.50 × 0.75 m)"),
        ("path length per lap", "3.142 m", "4.573 m"),
        ("lap time T<sub>lap</sub>", "24.0 s", "22.865 s"),
        ("<b>mean end-effector speed</b>", "<b>0.131 m/s</b>", "<b>0.200 m/s</b>"),
        ("peak end-effector speed", "0.131 m/s", "0.29 m/s"),
        ("run length T (one lap, 4 s ramps, s = 1)", "28.0 s", "26.86 s"),
        ("q<sub>2</sub> sinusoid", "25 ± 15°, P = 6.0 s", "25 ± 15°, P = 5.716 s"),
        ("q<sub>2</sub> periods per lap", "4", "4"),
        ("fold β<sub>e</sub> (q<sub>2</sub> + q<sub>3</sub> at rest)", "55°", "55°"),
        ("peak base yaw rate", "15.1°/s", "51.3°/s"),
        ("peak CoM speed / acceleration", "0.17 m/s / 0.075 m/s²", "0.28 m/s / 0.33 m/s²"),
        ("peak joint rate / joint torque (plan)", "15.7°/s / 0.84 N·m", "17.5°/s / 0.84 N·m"),
        ("planner bounds", "shared: v 0.30 m/s, a 0.15 m/s², yaw 0.30 rad/s",
         "v 0.30 m/s (shared); EE-run only: a 0.40 m/s², yaw 1.0 rad/s"),
        ("largest feasible time scale s<sub>max</sub> (binding bound)", "1.13 (yaw rate)", "1.06 (CoM speed)"),
        ("takeoff heading / placement", "0°, centred on the world origin",
         "45°, crossing at the hold's end-effector point, long axis on world x"),
    ]
    body = "\n".join(f"      <tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in rows)
    return f"""<div class="tbl wraptbl"><table>
    <thead><tr><th>parameter</th><th>circle (section 2)</th><th>figure-8 (section 3)</th></tr></thead>
    <tbody>
{body}
    </tbody>
  </table></div>
  <p class="note">Peaks are the planner's own numbers for the run at s = 1. The figure-8's peak yaw rate is 3.4× the circle's and its peak CoM acceleration 4.4×: the tangent turns 270° around each lobe, fastest at the top and bottom of a lobe, and the airframe swings around the end effector there.</p>"""


def sizing_table():
    # fig8_probe at 0.20 m/s mean, s = 1 (../analysis/sizing_candidates.txt); s_max at
    # v 0.30 (shared) / a 0.40 / yaw 1.0 rad/s (EE run only)
    rows = [
        ("0.60", "0.300", "3.658", "18.29", "4.573", "0.329", "0.465", "64.6", "0.89 (CoM speed)"),
        ("0.65", "0.325", "3.963", "19.82", "4.954", "0.310", "0.413", "59.5", "0.97 (CoM speed)"),
        ("0.70", "0.350", "4.268", "21.34", "5.335", "0.294", "0.366", "55.2", "1.02 (CoM speed)"),
        ("<b>0.75</b>", "<b>0.375</b>", "<b>4.573</b>", "<b>22.86</b>", "<b>5.716</b>", "<b>0.280</b>",
         "<b>0.327</b>", "<b>51.3</b>", "<b>1.07 (CoM speed)</b>"),
        ("0.75", "0.300", "4.139", "20.69", "5.174", "0.275", "0.310", "48.0", "1.08 (CoM speed)"),
        ("0.75", "0.225", "3.744", "18.72", "4.680", "0.266", "0.296", "45.1", "1.12 (CoM speed)"),
    ]
    body = "\n".join("      <tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f"""<div class="tbl wraphead"><table>
    <thead><tr><th>A [m]</th><th>B [m]</th><th>path [m]</th><th>T<sub>lap</sub> at 0.20 m/s [s]</th><th>q<sub>2</sub> period T<sub>lap</sub>/4 [s]</th><th>peak CoM speed [m/s]</th><th>peak CoM accel. [m/s²]</th><th>peak yaw rate [°/s]</th><th>s<sub>max</sub> (binding bound)</th></tr></thead>
    <tbody>
{body}
    </tbody>
  </table></div>"""


def sweep_table(sizing, env, recommend):
    """The 3.1 table: every candidate (A, v) -- planner numbers, the simulated tracking of both
    controllers, the flight prediction (/ ratio) and the 2 x 2 m footprint check."""
    g = {(e["rig"], round(float(e["shape"][1:]), 2), round(e["speed"], 2)): e for e in env}
    def mm(e, k):
        return f"{e[k]:.0f}"
    def marg(e):
        v = e["margin_m"] * 1e3
        return f'<span class="{"okc" if v >= 0 else "bad"}">{v:+.0f}</span>'
    rows = []
    for r in sizing:
        key = (round(r["A"], 2), round(r["v"], 2))
        w, d = g.get(("wb",) + key), g.get(("decoupled",) + key)
        cls = ' class="rec"' if key == recommend else ""
        bs = f"{r['B']:.3f}".rstrip("0")
        bs = bs if len(bs.split(".")[1]) >= 2 else f"{r['B']:.2f}"
        head = (f"<td class=\"nw\">{r['A']:.2f} × {bs}</td><td>{r['v']:.2f}</td><td>{r['lap']:.1f} / {r['q2_period']:.2f}</td>"
                f"<td>{r['peak_yaw_degs']:.0f} / {r['peak_a']:.2f}</td><td>{r['s_max']:.2f}</td>")
        if r["s_max"] < 1.0:
            rows.append(f"      <tr{cls}>{head}<td colspan=\"5\" class=\"note\">not plannable at s = 1: peak CoM speed "
                        f"{r['peak_v']:.2f} m/s &gt; v<sub>max</sub> 0.30</td></tr>")
        elif w is None or d is None:
            rows.append(f"      <tr{cls}>{head}<td colspan=\"5\" class=\"note\">not flown</td></tr>")
        else:
            rows.append(f"      <tr{cls}>{head}<td>{w['ee_rms']:.1f} / {mm(w, 'ee_peak')}</td><td>{d['ee_rms']:.1f} / {mm(d, 'ee_peak')}</td>"
                        f"<td>{mm(w, 'ee_peak_flight')} / {mm(d, 'ee_peak_flight')}</td>"
                        f"<td>{w['pred_box'][0]:.2f} × {w['pred_box'][1]:.2f} / {d['pred_box'][0]:.2f} × {d['pred_box'][1]:.2f}</td>"
                        f"<td>{marg(w)} / {marg(d)}</td></tr>")
    body = "\n".join(rows)
    return f"""<div class="tbl wraphead"><table>
    <thead><tr><th>A × B [m]</th><th>mean EE speed [m/s]</th><th>lap / q<sub>2</sub> period [s]</th><th>peak yaw rate [°/s] / CoM accel. [m/s²]</th><th>s<sub>max</sub></th><th>simulated EE rms / peak, whole-body [mm]</th><th>simulated EE rms / peak, geometric [mm]</th><th>predicted flight EE peak (÷ 0.6), WB / geo [mm]</th><th>predicted footprint, WB / geo [m]</th><th>margin per side in 2 × 2 m, WB / geo [mm]</th></tr></thead>
    <tbody>
{body}
    </tbody>
  </table></div>"""


def fmt(x, n=2):
    return f"{x:.{n}f}"


def results_table(sc, labels):
    def row(lab, r, cls=""):
        j = " / ".join(fmt(v) for v in r["joint_rms_deg"])
        c = f' class="{cls}"' if cls else ""
        return (f"      <tr{c}><td>{lab}</td><td>{fmt(r['ee_pos_rms_mm'])}</td><td>{fmt(r['ee_pos_max_mm'], 1)}</td>"
                f"<td>{fmt(r['ee_head_rms_deg'])}</td><td>{fmt(r['base_pos_rms_mm'])}</td><td>{fmt(r['base_yaw_rms_deg'])}</td>"
                f"<td>{j}</td><td>{fmt(r['tilt_max_deg'], 1)}</td></tr>")
    out = []
    for rig, name, cls in (("wb", "Whole-body L1", "wb"), ("decoupled", "Geometric L1 adaptive", "geo")):
        labs = [l for l in labels if sc[l]["rig"] == rig]
        out.append(f'      <tr class="grp"><td colspan="8"><span class="sw {cls}"></span>{name}</td></tr>')
        for l in labs:
            out.append(row(l, sc[l]))
        mean = {k: float(np.mean([sc[l][k] for l in labs])) for k in
                ("ee_pos_rms_mm", "ee_pos_max_mm", "ee_head_rms_deg", "base_pos_rms_mm", "base_yaw_rms_deg", "tilt_max_deg")}
        mean["joint_rms_deg"] = list(np.mean([sc[l]["joint_rms_deg"] for l in labs], axis=0))
        out.append(row("mean", mean, "mean"))
    body = "\n".join(out)
    return f"""<div class="tbl wraphead"><table>
    <thead><tr><th>flight</th><th>EE position [mm]</th><th>EE position peak [mm]</th><th>EE heading [deg]</th><th>base position [mm]</th><th>base heading / yaw [deg]</th><th>joints q1 / q2 / q3 / q4 [deg]</th><th>peak tilt [deg]</th></tr></thead>
    <tbody>
{body}
    </tbody>
  </table></div>"""


import numpy as np  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scores", required=True)
    ap.add_argument("--mech", required=True)
    ap.add_argument("--top", required=True)
    ap.add_argument("--series", required=True)
    ap.add_argument("--budget", required=True, help="fig8_budget.py json: figure-8 labels + circle labels prefixed c-")
    ap.add_argument("--sizing", required=True, help="../analysis/sizing_sweep.json (planner numbers per candidate)")
    ap.add_argument("--envelope", required=True, help="fig8_envelope.py json (all flown candidates)")
    ap.add_argument("--recommend", nargs=2, type=float, metavar=("A", "V"), required=True)
    ap.add_argument("--findings", required=True, help="HTML fragment: the sweep findings + recommendation")
    ap.add_argument("--trips", default="", help="one sentence on flights that tripped before their run")
    ap.add_argument("--section3", required=True, help="the section-3 prose template (HTML with {placeholders})")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    sc = json.load(open(a.scores)); mech = json.load(open(a.mech)); bud = json.load(open(a.budget))
    labels = list(sc.keys())
    html = open(V8).read()

    # --- head: math CSS, lede ------------------------------------------------
    html = html.replace("</style>", CSS + "</style>", 1)
    old_lede_start = html.index('<p class="lede">')
    old_lede_end = html.index("</p>", old_lede_start) + 4
    lede = ('<p class="lede">Three controllers flew the same end-effector circle (radius 0.5 m, 24 s lap, the arm\'s '
            'second joint swinging 25 ± 15° on a 6 s period), and two of them then flew a faster figure-8 (1.5 × 0.75 m, '
            '0.20 m/s mean end-effector speed, 3.4× the circle\'s peak yaw rate). All flights used one Isaac plant built '
            'from identified flight disturbances, one trajectory planner and one SAFETY takeoff/landing loop. The controllers '
            'are our whole-body L1 impedance law; the geometric controller with L1 adaptive augmentation of Cai et al. '
            '(CEP 2025); and the modular adaptive law of Yadav et al. (TMECH 2025). Only the DIRECT control law differed, '
            'plus, for the geometric law, how the arm is driven: its paper treats the arm separately, so the arm runs a '
            'position-mode stack tracking the planner\'s joint reference, where the other two command arm torques. All '
            'results are from Isaac running at real time (RTF 1). The whole-body law flew its shipped configuration, which '
            'was tuned on this plant\'s offline bench; the geometric and modular laws were implemented from their papers and '
            'tuned for this plant on the same bench with the same search. Section 1 gives the reference trajectories.</p>')
    html = html[:old_lede_start] + lede + html[old_lede_end:]
    h1 = "<h1>Whole-body L1 impedance vs geometric L1 adaptive vs modular adaptive control</h1>"
    assert h1 in html

    # --- renumber v8: 1 -> 2 (circle), 2 -> 4 (settings) ----------------------
    html = html.replace('<section aria-label="Tracking performance comparison">',
                        '<section aria-label="Circle tracking performance comparison">', 1)
    html = html.replace("<h2>1. Tracking performance comparison</h2>",
                        "<h2>2. Circle: tracking performance comparison</h2>", 1)
    html = html.replace("<h2>2. Simulation settings</h2>", "<h2>4. Simulation settings</h2>", 1)
    for o, n in (("<h3>2.1 ", "<h3>4.1 "), ("<h3>2.2 ", "<h3>4.2 "), ("<h3>2.3 ", "<h3>4.3 ")):
        assert html.count(o) == 1, o
        html = html.replace(o, n)
    html = html.replace("(section 2.3)", "(section 4.3)")
    html = html.replace("All nine flights ran under one condition", "All nine circle flights ran under one condition")

    # --- section 1 before the circle, section 3 after it ----------------------
    s1 = section_reference().replace("__PARAMTABLE__", param_table(sc))
    i = html.index('<section aria-label="Circle tracking performance comparison">')
    html = html[:i] + s1 + "\n" + html[i:]
    s3 = open(a.section3).read()
    wb = [l for l in labels if sc[l]["rig"] == "wb"]; geo = [l for l in labels if sc[l]["rig"] == "decoupled"]
    mean = lambda labs, k: float(np.mean([sc[l][k] for l in labs]))  # noqa: E731
    mmean = lambda labs, k: float(np.mean([mech[l][k] for l in labs]))  # noqa: E731
    vals = dict(
        SIZING=sweep_table(json.load(open(a.sizing)), json.load(open(a.envelope)),
                           (round(a.recommend[0], 2), round(a.recommend[1], 2))),
        RESULTS=results_table(sc, labels),
        SWEEP_FINDINGS=open(a.findings).read(), TRIPS=a.trips,
        TOP=img64(a.top), SERIES=img64(a.series),
        n_wb=len(wb), n_geo=len(geo),
        wb_ee=fmt(mean(wb, "ee_pos_rms_mm"), 1), geo_ee=fmt(mean(geo, "ee_pos_rms_mm"), 1),
        wb_head=fmt(mean(wb, "ee_head_rms_deg")), geo_head=fmt(mean(geo, "ee_head_rms_deg")),
        wb_eemax=fmt(max(sc[l]["ee_pos_max_mm"] for l in wb), 0), geo_eemax=fmt(max(sc[l]["ee_pos_max_mm"] for l in geo), 0),
        wb_headmax=fmt(max(sc[l]["ee_head_max_deg"] for l in wb), 1), geo_headmax=fmt(max(sc[l]["ee_head_max_deg"] for l in geo), 1),
        wb_base=fmt(mean(wb, "base_pos_rms_mm"), 1), geo_base=fmt(mean(geo, "base_pos_rms_mm"), 1),
        wb_tilt=fmt(max(sc[l]["tilt_max_deg"] for l in wb), 1), geo_tilt=fmt(max(sc[l]["tilt_max_deg"] for l in geo), 1),
        wb_tau=fmt(max(sc[l].get("tau_joint_peak", float("nan")) for l in wb), 2),
        geo_mot_lo=fmt(min(sc[l]["motor_min"] for l in geo), 2), geo_mot_hi=fmt(max(sc[l]["motor_max"] for l in geo), 2),
        ratio_ee=fmt(mean(geo, "ee_pos_rms_mm") / mean(wb, "ee_pos_rms_mm"), 1),
        ratio_head=fmt(mean(geo, "ee_head_rms_deg") / mean(wb, "ee_head_rms_deg"), 1),
        geo_slope=fmt(-mmean(geo, "head_slope_s"), 3), geo_r2=fmt(mmean(geo, "head_r2"), 2),
        wb_slope=fmt(mmean(wb, "head_slope_s"), 3),
        wb_hi=fmt(mmean(wb, "ee_rms_highrate_mm"), 1), wb_lo=fmt(mmean(wb, "ee_rms_lowrate_mm"), 1),
        geo_hi=fmt(mmean(geo, "ee_rms_highrate_mm"), 1), geo_lo=fmt(mmean(geo, "ee_rms_lowrate_mm"), 1),
        geo_off=fmt(mmean(geo, "hover_offset_mm"), 0), wb_off=fmt(mmean(wb, "hover_offset_mm"), 1),
        wb_along=fmt(mean(wb, "along_mean_mm"), 1), geo_along=fmt(mean(geo, "along_mean_mm"), 1),
        wb_cross=fmt(mean(wb, "cross_rms_mm"), 1), geo_cross=fmt(mean(geo, "cross_rms_mm"), 1),
        wb_crossm=fmt(mean(wb, "cross_mean_mm"), 1), geo_crossm=fmt(mean(geo, "cross_mean_mm"), 1),
        geo_crossm_abs=fmt(abs(mean(geo, "cross_mean_mm")), 0), geo_along_r=fmt(mean(geo, "along_mean_mm"), 0),
    )
    bmean = lambda labs, k: float(np.mean([bud[l][k] for l in labs]))  # noqa: E731
    cw = [k for k in bud if k.startswith("c-WB")]; cg = [k for k in bud if k.startswith("c-GEO")]
    cmech_w = [k for k in mech if k.startswith("c-WB")]; cmech_g = [k for k in mech if k.startswith("c-GEO")]
    for tag, labs in (("wb", wb), ("geo", geo), ("wbc", cw), ("geoc", cg)):
        vals[f"{tag}_af"] = fmt(bmean(labs, "airframe"), 1)
        vals[f"{tag}_att"] = fmt(bmean(labs, "attitude"), 1)
        vals[f"{tag}_j"] = fmt(bmean(labs, "joints"), 1)
    vals["wbc_slope"] = fmt(mmean(cmech_w, "head_slope_s"), 3)
    vals["geoc_slope"] = fmt(-mmean(cmech_g, "head_slope_s"), 3)
    vals["geo_att_pred"] = fmt(1e3 * 0.25 * np.radians(mean(geo, "ee_head_rms_deg")), 0)
    for k, v in vals.items():
        v = str(v)
        if len(v) < 12 and v.startswith("-"):
            v = "\u2212" + v[1:]          # typographic minus for numbers
        s3 = s3.replace("{" + k + "}", v)
    left = re.findall(r"\{[a-zA-Z_0-9]+\}", s3)
    assert not left, left
    i = html.index('<section aria-label="Simulation settings">')
    html = html[:i] + s3 + "\n" + html[i:]

    # --- footer ----------------------------------------------------------------
    foot = ('  <div>Figure-8 campaign: <code>docs/docs_aerial_manipulator/archive/figure8_compare_20261005/</code> '
            '(sizing probe <code>tools/fig8_probe.cpp</code> on the planner library, flights <code>run_fig8.sh</code>, '
            'scores <code>tools/fig8_score.py</code>, <code>tools/fig8_mechanism.py</code>, figures <code>tools/fig8_figures.py</code>, '
            'this page <code>tools/build_report.py</code>) · Commands: Command.md §14</div>\n')
    i = html.index("<footer>") + len("<footer>\n")
    html = html[:i] + foot + html[i:]
    open(a.out, "w").write(html)
    print("wrote", a.out, len(html), "bytes")


if __name__ == "__main__":
    main()
