#!/usr/bin/env python3
"""Generate the PUSH-AND-PULL sim config from the 4-D mirror sim config.

    /usr/bin/python3 make_push_pull_yaml.py [--check]

  in : fsc_autopilot_ros2/config/params_single_aerial_manipulator_whole_body_l1_4d_direct_actuation_t650_sim.yaml
  out: fsc_autopilot_ros2/config/params_single_aerial_manipulator_whole_body_l1_4d_direct_actuation_t650_sim_push_pull.yaml

The output is the mirror file BYTE FOR BYTE, plus
  * a header saying what differs (above the mirror's own header),
  * vehicle_name -> AM-T650-WB-L1-4D-PUSH,
  * every key in OVERRIDES replaced in place (each must exist exactly once),
  * the push-and-pull planner block appended to the trajectory planner's section
    (the mirror's last section).
So the plant (section 1) and the rest of the controller can never drift from
the mirror except where this script says so. Regenerate after any edit to the
mirror; never hand-edit the output. --check verifies that the file on disk is
what this script would write.

THE BOX IS AN INTERACTION, NOT MODEL UNCERTAINTY -- the opposite of the
pick-and-place payload. wb_l1_contact stays false at startup (chi = free, as the
mirror flies); the PLANNER switches it to CONTACT through the whole-body node's
set_contact service from the claw's arrival on the handle (end of Ready; it was
the Push press until the first flight, 2026-10-04) to the Exit / Abort press, so the handle's
reaction is the task wrench the 4-D attribution reads and the EE impedance renders
(compliance) instead of an internal disturbance the observer cancels (stiffness --
which drove q3 to its +50 deg stop under sustained pushes >= 3 N in the
2026-09-27 interaction campaign).
"""
import argparse
import os
import re
import sys

CFG = os.path.expanduser("~/ros2_ws/src/fsc_autopilot_ros2/config")
SRC = os.path.join(CFG, "params_single_aerial_manipulator_whole_body_l1_4d_direct_actuation_t650_sim.yaml")
DST = os.path.join(CFG, "params_single_aerial_manipulator_whole_body_l1_4d_direct_actuation_t650_sim_push_pull.yaml")
VEHICLE_NAME = "AM-T650-WB-L1-4D-PUSH"

# Controller keys that differ from the mirror (name -> YAML value text).
#
# wb_k_r / wb_k_w 2.134 / 1.567 -> 1.6 / 1.2: the pick-and-place pair (both x0.75,
# the same damping ratio), flown 3 / 3 full pick-and-place missions with the arm
# in this same claw-down pose (pick_place_controllers_20261003, wb_1..3). H1b's
# lightly damped 1.5 Hz pitch mode grew to 8-12 deg in 2 of 8 pick-and-place
# hovers. (That campaign is evaluating 1.4 / 1.5 as of 2026-10-03; not adopted
# here until it reports.)
#
# THE CONTACT READING SPLIT (interaction campaign 2026-09-27, README "Results"):
# H1b's scalar wb_l1_omega_x 0.2072 filters BOTH the rendered contact force and
# u3's feed-forward, so a contact force is rendered with a 4.8 s lag; the
# reading at 2.0 rad/s with the feed-forward kept at 0.2072 per block fixes it
# (static contact rendered 96-103 %, deflection F / K_y within ~1 mm in Isaac),
# and FREE FLIGHT IS IDENTICAL (the reading is gated to zero there).
OVERRIDES = {
    "wb_k_r": "1.6",
    "wb_k_w": "1.2",
    "wb_l1_omega_x": "2.0",
    "wb_l1_omega_x_t": "0.2072",
    "wb_l1_omega_x_r": "0.2072",
    "wb_l1_omega_x_q": "0.2072",
}
# Controller keys the mirror does not carry (they default off in the node),
# inserted after the named anchor key: name -> (anchor, YAML value text).
#
# wb_l1_contact_hold_translation (2026-10-04): the node's option to HOLD the
# CoM observer's rows in contact. Written out FALSE on purpose: it was needed
# only with the CoM anchor (pl_1: the CoM loop integrated the stuck box's
# reaction -- 51 mm of drift on a fixed reference, then a stick-slip cycle);
# with the claw WORLD-held through the push (push_pull_world_anchor_push) base
# drift no longer loads the box, and holding the rows instead let the base sit
# 25 mm off its plan and stretched the arm to the wrist singularity (pl_4).
ADDITIONS = {
    "wb_l1_contact_hold_translation": ("wb_l1_collision_threshold_n", "false"),
}
# what the generator refuses: the startup phase flag must stay free (the
# planner owns it), and the threshold fallback off (an unannounced-collision
# latch would fight the planner's flag)
MUST_KEEP = {"wb_l1_contact": "false", "wb_l1_collision_threshold_n": "0.0", "wb_l1_four_d": "true"}

PLANNER_BLOCK = """
    # --- push-and-pull mode (arm GS "Push & Pull" tab), 2026-10-03 ---------
    # GENERATED by fsc_PegasusSimulator/docs/docs_aerial_manipulator/
    # archive/push_pull_20261003/tools/make_push_pull_yaml.py -- edit there.
    # Scene: application/robotic_arm/07_px4_direct_t650_aerial_manipulator_push_and_pull.py
    # -- the HOOBRO BB52UXG01G1 console table (1.000 x 0.150 x 0.800 m) in front
    # of the start, its length along y; a 200 g, 200 x 100 x 60 mm box near its
    # +y end (mocap obj_0 = the box centre + yaw) with a 20 mm fin handle on its
    # +y face, 90 mm out, 20..110 mm above the table top.
    #
    # The grasp point: the box centre + this offset in the box frame -- 100 mm
    # half box + 55 mm along the fin, 30 mm half box + 35 mm up the fin (15 mm
    # under its top, the pick's grasp depth). The drone faces the box's -y
    # (yaw_from_box -90): the jaws then close along the box's x, across the fin.
    push_pull_ee_offset: [0.0, 0.155, 0.065]
    push_pull_yaw_from_box_deg: -90.0
    # The arm in the push: the pick pose -- claw pitched 10 deg forward, 0.130 m
    # ahead of / 0.316 m under the body origin, sigma_nd 0.298 -- held FIXED
    # through the push. With the grasp 0.895 m up, the body origin is at 1.211 m
    # and the landing gear's skids 9.8 cm ABOVE the table top (they also
    # straddle the 150 mm table and the 100 mm box laterally).
    push_pull_push_pose_deg: [0.0, -20.0, 30.0, 0.0]
    # Safety margin: Go To Start holds the claw this far above the grasp point,
    # Ready To Push descends it, Exit To Push climbs it.
    push_pull_approach_dz: 0.20
    # The push: 0.50 m along the nose (-y), >= 12 s (peak ~0.09 m/s), after a
    # 1.5 s hold. CONTACT is on from the claw's arrival on the handle (end of
    # Ready). The box's friction is ~1.2 N, the same to break it loose as to
    # keep it sliding (scene: mu_s = mu_k = 0.6 x 200 g -- a box that sticks
    # and then lets go surged the base 7 cm in pl_5).
    push_pull_push_distance: 0.50
    push_pull_push_time_s: 12.0
    push_pull_push_settle_s: 1.5
    push_pull_exit_time_s: 3.0
    # The claw stays held in the WORLD through the push (2026-10-04): with the
    # CoM anchor a base offset dragged the claw reference against the stuck box
    # and the platform observer pushed through its static friction (pl_1..3).
    push_pull_world_anchor_push: true
    # Land: 0.5 m behind the start, yaw -360 = 270 deg CLOCKWISE on from the push
    # heading -90 (the whole mission turns one full circle clockwise). Adjust
    # (vehicle on its start mark) writes the measured x, y shift into both.
    push_pull_land: [-0.5, 0.0, 0.8, -360.0]
    push_pull_start_mark: [0.0, 0.0, 1.0, 0.0]
    # THE TABLE keep-out [x_min, x_max, y_min, y_max, z_top] (world): the gear
    # (0.313 m under the body origin, 0.25 m radius) and every arm point over the
    # top keep 5 cm clearance on every planned path.
    push_pull_table: [1.125, 1.275, -0.5, 0.5, 0.80]
    push_pull_table_clearance: 0.05
    # Isaac has no ceiling (the lab's must be set on hardware)
    push_pull_fence_max_z: 2.2
    # SAFETY GUARDS -> ABORT (contact off, release, climb 0.30 m, arm home):
    # tilt > 15 deg for 0.1 s; the task force the law reads > 5 N for 0.3 s while
    # in contact (~4x the box's friction; the bench's along-arm capacity ~6 N).
    push_pull_guard_tilt_deg: 15.0
    push_pull_guard_force_n: 5.0
"""

HEADER = """# =============================================================================
# GENERATED -- DO NOT EDIT. Source: the 4-D mirror sim yaml (below, byte for
# byte) + fsc_PegasusSimulator/docs/docs_aerial_manipulator/archive/push_pull_20261003/
# tools/make_push_pull_yaml.py. Regenerate after any edit to the mirror.
#
# PUSH-AND-PULL, whole-body 4-D L1 (WB_SIM_PROFILE=push_pull). Differs from the
# mirror only in:
#   * vehicle_name AM-T650-WB-L1-4D-PUSH
#   * controller overrides: wb_k_r 1.6, wb_k_w 1.2 (the pick-and-place pair),
#     wb_l1_omega_x 2.0 + wb_l1_omega_x_t/r/q 0.2072 (the contact reading split),
#     wb_l1_contact_hold_translation false (written out; see the generator)
#   * the push-and-pull planner block (end of the planner section)
# wb_l1_contact stays false at startup: the PLANNER switches it to CONTACT from
# the claw's arrival on the handle (end of Ready) to the Exit / Abort press
# (set_contact).
# =============================================================================
"""


def build():
    with open(SRC) as f:
        text = f.read()
    if "push_pull_" in text:
        raise SystemExit("the mirror already carries push_pull_* keys -- nothing to generate onto")
    out = text
    n = len(re.findall(r'^    vehicle_name: "[^"]*"', out, flags=re.M))
    if n != 1:
        raise SystemExit(f"vehicle_name found {n} times in the mirror")
    out = re.sub(r'^    vehicle_name: "[^"]*"', f'    vehicle_name: "{VEHICLE_NAME}"', out, flags=re.M)
    for key, val in OVERRIDES.items():
        pat = re.compile(rf"^    {re.escape(key)}: [^\n#]*?(\s*#.*)?$", re.M)
        hits = pat.findall(out)
        if len(hits) != 1:
            raise SystemExit(f"{key}: found {len(hits)} times in the mirror (need exactly 1)")
        out = pat.sub(f"    {key}: {val}  # PUSH-AND-PULL OVERRIDE -- make_push_pull_yaml.py", out)
    for key, (anchor, val) in ADDITIONS.items():
        if re.search(rf"^    {re.escape(key)}:", out, flags=re.M):
            raise SystemExit(f"{key}: the mirror already carries it -- move it to OVERRIDES")
        pat = re.compile(rf"^(    {re.escape(anchor)}: [^\n]*\n)", re.M)
        if len(pat.findall(out)) != 1:
            raise SystemExit(f"{anchor}: the insertion anchor must exist exactly once")
        out = pat.sub(lambda m: m.group(1) + f"    {key}: {val}  # PUSH-AND-PULL ADDITION -- make_push_pull_yaml.py\n", out)
    for key, val in MUST_KEEP.items():
        m = re.search(rf"^    {re.escape(key)}: ([^\s#]+)", out, flags=re.M)
        if m is None or m.group(1) != val:
            raise SystemExit(f"{key} must be {val} in the mirror (got {m.group(1) if m else 'nothing'})")
    # the planner section is the mirror's LAST: append the block at the end
    last = out.rstrip("\n").rfind("\n/**/")
    if last < 0 or "whole_body_trajectory_planner:" not in out[last:last + 60]:
        raise SystemExit("the trajectory planner's section is not the mirror's last -- update the generator")
    return HEADER + out.rstrip("\n") + "\n" + PLANNER_BLOCK


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify the file on disk, write nothing")
    a = ap.parse_args()
    want = build()
    if a.check:
        have = open(DST).read() if os.path.exists(DST) else ""
        print("UP TO DATE" if have == want else f"STALE: {DST} differs from what this script writes")
        sys.exit(0 if have == want else 1)
    with open(DST, "w") as f:
        f.write(want)
    print(f"wrote {DST}")


if __name__ == "__main__":
    main()
